# Generated by Django 6.1 on 2026-08-15 14:33

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medical_records', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_id', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('generic_name', models.CharField(blank=True, max_length=150)),
                ('category', models.CharField(max_length=100)),
                ('manufacturer', models.CharField(blank=True, max_length=150)),
                ('batch_number', models.CharField(max_length=50)),
                ('expiry_date', models.DateField()),
                ('purchase_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('selling_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('stock_quantity', models.PositiveIntegerField(default=0)),
                ('minimum_stock_level', models.PositiveIntegerField(default=10)),
                ('supplier', models.CharField(blank=True, max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prescription_id', models.CharField(max_length=20, unique=True)),
                ('dosage', models.CharField(max_length=100)),
                ('frequency', models.CharField(max_length=100)),
                ('duration_days', models.PositiveIntegerField()),
                ('quantity', models.PositiveIntegerField()),
                ('instructions', models.TextField(blank=True)),
                ('prescribed_date', models.DateField(auto_now_add=True)),
                ('medical_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='medical_records.medicalrecord')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescriptions', to='pharmacy.medicine')),
            ],
            options={
                'ordering': ['-prescribed_date'],
            },
        ),
    ]
